---
title: "Insighter 사전"
author: "전희원(Heewon Jeon)"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    fig_width: 6
    fig_height: 8.5
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


## 사전 현황 

```{r,echo=F,message=FALSE}
library(ggplot2)
library(NIADic)
library(data.table)
library(scales)

total_dt <- data.table(get_dic("insighter"))
```

- 전체 `r format(nrow(total_dt), big.mark=',')`개의 단어
- 위치, 브랜드, 인명 세부 카테고리 포함 



### 품사/카테고리별 통계량  

- 카테고리 정보에 품사 정보가 섞여있을 수 있음 

```{r,echo=FALSE}

ggplot(total_dt[,.N,.(tag)], aes(x=reorder(tag, N), N)) +geom_bar(stat='identity') + xlab("KAIST tag") + coord_flip() + ggtitle("Tag frequency") + scale_y_continuous(labels = comma)


ggplot(total_dt[,.N,in_category], aes(x=reorder(in_category, N), N)) +geom_bar(stat='identity') + xlab("category") + coord_flip() + ggtitle("NIA dictionary  category frequency") +  scale_y_continuous(labels = comma)

```


### 카테고리 단어 예시(위치, 브랜드명) 


```{r, echo=FALSE}
knitr::kable(total_dt[in_category %chin% 'place_name'][sample(nrow(total_dt[in_category %chin% 'place_name']), 10)], caption="위치 예시")

knitr::kable(total_dt[in_category %chin% 'brand_name'][sample(nrow(total_dt[in_category %chin% 'brand_name']), 10)],  caption="브랜드명 예시")

```
